app = "connect4-server"

[build]
  image = "python:3.10-slim"

[env]
  REDIS_URL = "redis://default:<password>@<your-upstash-url>:port"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = 80
